name: weather_mark
description: A weather mark app
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  auth0_flutter: ^1.7.2
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  dio: ^5.8.0+1
  auto_injector: ^1.0.2
  flutter_map: ^8.1.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  path: ^1.9.0
  latlong2: ^0.9.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.5.3
dev_dependencies:

  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_dotenv: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
 
  image_path: "assets/logo.png" # <-- tu ícono (1024x1024 recomendado)

flutter_native_splash:
  color: "#ffffff" # o background_image
  image: assets/logo.png # <-- tu logo (recomendado 512x512 o más)
  android: true
 
  fullscreen: true
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
